export * from './types';
export {
  adapters,
  remotiveAdapter,
  ashbyAdapter,
  greenhouseAdapter,
  leverAdapter,
  smartRecruitersAdapter,
  workableAdapter,
  adzunaAdapter,
  arbeitnowAdapter,
  firecrawlAdapter,
  workdayAdapter,
  icimsAdapter,
  successFactorsAdapter,
  createAshbyAdapter,
  createGreenhouseAdapter,
  createLeverAdapter,
  createSmartRecruitersAdapter,
  createWorkableAdapter,
  createAdzunaAdapter,
  createArbeitnowAdapter,
  createFirecrawlAdapter,
  createWorkdayAdapter,
  createIcimsAdapter,
  createSuccessFactorsAdapter,
  mapRemotive,
  mapAshby,
  mapGreenhouse,
  mapLever,
  mapSmartRecruiters,
  mapWorkable,
  mapAdzuna,
  mapArbeitnow,
  mapFirecrawl,
  mapWorkday,
  mapIcims,
  mapSuccessFactors,
  inferLeverRemote,
  titleFromPortalUrl,
  parseIcimsDate,
  isBannedPlatformUrl,
  companyFromUrl,
  firecrawlRateLimit,
  workdayRateLimit,
  leverRateLimit,
  smartRecruitersRateLimit,
  workableRateLimit,
  icimsRateLimit,
  successFactorsRateLimit,
  parseWorkdayPosted,
  inferWorkdayRemote,
  FIRECRAWL_TRUST_TIER,
  FIRECRAWL_SOURCE_NAME,
  LEVER_SOURCE_NAME,
  LEVER_DEFAULT_PAGE_SIZE,
  SMARTRECRUITERS_SOURCE_NAME,
  SMARTRECRUITERS_DEFAULT_PAGE_SIZE,
  SMARTRECRUITERS_DEFAULT_MAX_DETAILS,
  WORKABLE_SOURCE_NAME,
  WORKABLE_DEFAULT_MAX_JOBS,
  WORKDAY_SOURCE_NAME,
  WORKDAY_TRUST_TIER_UNVERIFIED,
  WORKDAY_TRUST_TIER_VERIFIED,
  WORKDAY_DEFAULT_PAGE_SIZE,
  ICIMS_SOURCE_NAME,
  ICIMS_TRUST_TIER_UNVERIFIED,
  ICIMS_TRUST_TIER_VERIFIED,
  ICIMS_DEFAULT_PORTAL_ID,
  ICIMS_DEFAULT_PAGE_SIZE,
  SUCCESSFACTORS_SOURCE_NAME,
  SUCCESSFACTORS_TRUST_TIER_UNVERIFIED,
  SUCCESSFACTORS_TRUST_TIER_VERIFIED,
  SUCCESSFACTORS_DEFAULT_PAGE_SIZE,
  AdapterError,
  MalformedResponseError,
  MissingCredentialError,
  createConfiguredAdapter,
  type ProviderCredentials,
  type AshbyAdapterOpts,
  type GreenhouseAdapterOpts,
  type LeverAdapterOpts,
  type SmartRecruitersAdapterOpts,
  type WorkableAdapterOpts,
  type AdzunaAdapterOpts,
  type ArbeitnowAdapterOpts,
  type FirecrawlAdapterOpts,
  type FirecrawlJobClient,
  type WorkdayAdapterOpts,
  type IcimsAdapterOpts,
  type SuccessFactorsAdapterOpts,
  type WorkdayJobPosting,
  type WorkdayDetail,
  type WorkdayMapContext,
  type SuccessFactorsJob,
  type SuccessFactorsMapContext,
  type IcimsSearchResult,
  type AshbyJob,
  type GreenhouseJob,
  type LeverPosting,
  type SmartRecruitersPosting,
  type WorkableJob,
  type AdzunaJob,
  type ArbeitnowJob,
  type RemotiveJob,
} from './adapters';
export { normalize, type NormalizedJob, type NormalizeInput } from './stages/normalize';
export {
  classifySeniority,
  type SeniorityLevel,
  type SeniorityResult,
} from './stages/classify-seniority';
export {
  classifyRole,
  type RoleFamily,
  type RoleResult,
} from './stages/classify-role';
export { parseCompBand } from './stages/comp-band';
export {
  convertToUsd,
  convertToUsdBand,
  rates,
  type Money,
  type CompBand,
  type CompBandUsd,
  type RatesSnapshot,
} from './fx/rates';
export { dedupe, type DedupeResult } from './stages/dedupe';
export {
  planIngest,
  type IngestPlan,
  type RejectedIngestRow,
} from './stages/ingest-plan';
export {
  buildCandidateSearchQueries,
  containsBannedPlatformTerm,
  ATS_SITE_HINTS,
  BANNED_PLATFORM_TERMS,
  type CandidateSearchProfile,
  type BuildCandidateSearchQueriesOptions,
} from './search/query-builder';
export {
  runCandidateSearch,
  type CandidateSearchRunOptions,
  type CandidateSearchRunResult,
} from './search/candidate-search';
export {
  freshness,
  type FreshnessOpts,
  type FreshnessResult,
  type FreshnessReason,
} from './stages/freshness';
export {
  verify,
  type VerifyOpts,
  type VerifyResult,
  type VerifyVerdict,
} from './stages/verify';
export {
  trustOrder,
  tierFor,
  TIER_BY_ADAPTER,
  type TrustOrderOpts,
} from './stages/trust-order';
export {
  crossSourceDedupe,
  levenshtein,
  type CrossSourceDedupeOpts,
  type CrossSourceDedupeResult,
  type DuplicatePair,
} from './stages/cross-source-dedupe';
export {
  relevance,
  type RelevancePrefs,
  type RelevanceJob,
  type RelevanceOpts,
  type RelevanceReason,
  type RelevanceResult,
} from './stages/relevance';
export {
  computeMatch,
  computeMatchResult,
  type MatchResult,
  type MatchScore,
  type GapItem,
  type EvidenceRef,
  type Explanation,
  type RequiredSkill,
  type ComputeInput,
} from './stages/match';
// Wire-shape schemas per adapter (C-P3.6a). Used by contract tests + optional
// pre-parse guards. The `node:fs`-backed snapshot helpers in schemas.ts are
// intentionally NOT re-exported — they are test-time only.
export {
  RemotiveFeedWire,
  RemotiveJobWire,
  AshbyBoardWire,
  AshbyJobWire,
  GreenhouseBoardWire,
  GreenhouseJobWire,
  AdzunaResponseWire,
  AdzunaJobWire,
  ArbeitnowResponseWire,
  ArbeitnowJobWire,
  WorkdayJobsWire,
  WorkdayJobPostingWire,
  WorkdayDetailWire,
  FirecrawlSearchResponseWire,
  FirecrawlSearchResultWire,
  LeverBoardWire,
  LeverPostingWire,
  SmartRecruitersResponseWire,
  SmartRecruitersPostingWire,
  WorkableBoardWire,
  WorkableJobWire,
  IcimsSearchResponseWire,
  IcimsSearchResultWire,
  SuccessFactorsResponseWire,
  SuccessFactorsJobWire,
  adapterWireSchemas,
  type AdapterId,
} from './adapters/schemas';
