'use client';

import { useCallback, useState } from 'react';
import Link from 'next/link';
import { Briefcase, MessageSquareQuote, Sparkles, Wand2 } from 'lucide-react';
import { ThinkingOrb } from 'thinking-orbs';
import { Button } from '@careeros/ui';
import { Loader } from '@/components/Loader';
import { useApi } from '@/lib/use-api';
import {
  type TalkTrackResult,
  generateInterviewPrep,
  generateTalkTrack,
  getApplication,
  getInterviewPrep,
} from '@/lib/interview-prep';

/**
 * F.4 interview prep for one application. The plan and each talk-track are
 * generated by the real `/interview-prep/*` endpoints; talk-tracks already
 * passed the server-side fact-check gate before they are returned.
 */
export function InterviewPrepPanel({ applicationId }: { applicationId: string }) {
  const load = useCallback(async () => {
    const [prep, app] = await Promise.all([
      getInterviewPrep(applicationId),
      getApplication(applicationId),
    ]);
    return { prep, app };
  }, [applicationId]);
  const { data, error, refetch } = useApi(load);

  const [generating, setGenerating] = useState(false);
  const [topicBusy, setTopicBusy] = useState<string | null>(null);
  const [actionError, setActionError] = useState<string | null>(null);
  const [talkTrackNotice, setTalkTrackNotice] = useState<Record<string, string>>({});

  async function onGenerate() {
    setGenerating(true);
    setActionError(null);
    try {
      await generateInterviewPrep(applicationId);
      await refetch();
    } catch (e) {
      setActionError((e as Error).message);
    } finally {
      setGenerating(false);
    }
  }

  async function onTalkTrack(topicId: string) {
    setTopicBusy(topicId);
    setActionError(null);
    try {
      const result: TalkTrackResult = await generateTalkTrack(applicationId, topicId);
      if (!result.ok) {
        setTalkTrackNotice((n) => ({ ...n, [topicId]: result.reason ?? 'Talk-track refused.' }));
      } else {
        setTalkTrackNotice((n) => {
          const next = { ...n };
          delete next[topicId];
          return next;
        });
        await refetch();
      }
    } catch (e) {
      setActionError((e as Error).message);
    } finally {
      setTopicBusy(null);
    }
  }

  if (error) {
    return (
      <div role="alert" className="rounded-[var(--radius)] border border-danger/30 bg-danger/10 px-3.5 py-2.5 text-[13px] text-danger">
        {error}
      </div>
    );
  }
  if (data === null) return <Loader size={64} label="Loading prep plan" />;

  const { prep, app } = data;
  const talkTracks = prep?.talkTracks ?? {};

  return (
    <div className="flex flex-col gap-6" data-testid="interview-prep-panel">
      <div className="flex flex-wrap items-center justify-between gap-3 rounded-[var(--radius)] border border-[hsl(var(--border))] bg-[hsl(var(--bg-elev-1))] px-5 py-3">
        <div className="flex items-center gap-2 text-[13px] text-fg">
          <Briefcase className="h-4 w-4 text-fg-subtle" strokeWidth={1.7} />
          <span className="font-medium">{app?.jobTitle ?? 'Application'}</span>
          {app?.jobCompany && <span className="text-fg-muted">@ {app.jobCompany}</span>}
        </div>
        <div className="flex items-center gap-2">
          <Link href="/applications" className="text-[12px] text-fg-muted hover:text-fg">
            Back to applications
          </Link>
          <Button
            size="sm"
            variant={prep ? 'secondary' : 'primary'}
            data-testid="interview-prep-generate"
            onClick={onGenerate}
            disabled={generating}
          >
            {generating ? (
              <>
                <ThinkingOrb state="solving" size={20} /> Generating
              </>
            ) : (
              <>
                <Wand2 className="h-4 w-4" /> {prep ? 'Regenerate plan' : 'Generate prep plan'}
              </>
            )}
          </Button>
        </div>
      </div>

      {actionError && (
        <div role="alert" data-testid="interview-prep-error" className="text-[12.5px] text-danger">
          {actionError}
        </div>
      )}

      {!prep ? (
        <p
          data-testid="interview-prep-empty"
          className="rounded-[var(--radius)] border border-dashed border-[hsl(var(--border-strong))] bg-[hsl(var(--bg-elev-1))] px-6 py-10 text-center text-[13.5px] text-fg-muted"
        >
          No prep plan yet. Generate one to get the topics ranked by how likely they are and how
          strong your evidence is.
        </p>
      ) : (
        <ul className="flex flex-col gap-3" data-testid="interview-prep-topics">
          {prep.plan.topics.map((topic) => {
            const track = talkTracks[topic.id];
            return (
              <li
                key={topic.id}
                data-testid="interview-prep-topic"
                className="flex flex-col gap-3 rounded-[var(--radius)] border border-[hsl(var(--border))] bg-[hsl(var(--bg-elev-1))] px-5 py-4"
              >
                <div className="flex flex-wrap items-start justify-between gap-3">
                  <div className="flex flex-col gap-1">
                    <span className="text-[14px] font-medium text-fg">{topic.title}</span>
                    <span className="text-[12.5px] text-fg-muted">{topic.rationale}</span>
                    <span className="text-[11.5px] text-fg-faint">
                      {topic.source.replace(/_/g, ' ')} · {topic.suggestedDurationSec}s ·{' '}
                      {topic.evidenceFactIds.length} evidence ref
                      {topic.evidenceFactIds.length === 1 ? '' : 's'}
                    </span>
                  </div>
                  <Button
                    size="sm"
                    variant="ghost"
                    data-testid="interview-prep-talk-track"
                    disabled={topicBusy === topic.id}
                    onClick={() => onTalkTrack(topic.id)}
                  >
                    {topicBusy === topic.id ? (
                      <>
                        <ThinkingOrb state="composing" size={20} /> Drafting
                      </>
                    ) : (
                      <>
                        <MessageSquareQuote className="h-4 w-4" /> {track ? 'Redraft' : 'Talk-track'}
                      </>
                    )}
                  </Button>
                </div>

                {talkTrackNotice[topic.id] && (
                  <div
                    data-testid="interview-prep-topic-notice"
                    className="rounded-[var(--radius)] border border-warn/30 bg-warn/10 px-3.5 py-2.5 text-[12.5px] text-warn"
                  >
                    {talkTrackNotice[topic.id]}
                  </div>
                )}

                {track && (
                  <div
                    data-testid="interview-prep-talk-track-body"
                    className="flex flex-col gap-2 rounded-[var(--radius)] border border-[hsl(var(--border))] bg-[hsl(var(--bg))] px-4 py-3"
                  >
                    <span className="flex items-center gap-1.5 text-[11px] font-medium uppercase tracking-[0.08em] text-fg-subtle">
                      <Sparkles className="h-3.5 w-3.5" /> Draft · fact-check{' '}
                      {track.factCheck ?? 'unchecked'}
                    </span>
                    <p className="text-[13.5px] leading-relaxed text-fg">{track.draft}</p>
                    {track.cadenceNote && (
                      <p className="text-[12px] text-fg-faint">Cadence: {track.cadenceNote}</p>
                    )}
                    <span className="text-[11px] font-mono text-fg-faint">
                      {track.factRefs.join(', ')}
                    </span>
                  </div>
                )}
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
