// Heuristic scorer for the likelihood a commit was AI-assisted. Never a
// binary — downstream picks a cutoff. Signals compose additively then get
// squashed into [0..1].
//
// ponytail: string + numeric heuristics only. A model-based classifier
// (e.g. per-file diff embedding vs. author style) is the upgrade path when
// the false-positive rate on legitimate large refactors becomes a problem.

export interface CommitStat {
  sha: string;
  message: string;
  filesTouched: number;
  additions: number;
  deletions: number;
  authorEmail: string | null;
  authoredAt: Date;
}

export interface AiAssistHeuristicOptions {
  /** Optional author medians for calibration; when absent, hard-coded floors are used. */
  authorMedianLinesChanged?: number;
  authorMedianFilesTouched?: number;
}

export interface AiAssistScore {
  /** 0 = certainly human, 1 = strongly likely AI-assisted. */
  confidence: number;
  /** Ordered list of reason strings; empty when confidence is 0. */
  reasons: string[];
}

// Case-insensitive substrings that betray AI authorship in commit messages.
// The list stays short on purpose — false positives are silent (they nudge a
// confidence up), false negatives are recoverable by other signals.
export const AI_MESSAGE_MARKERS: string[] = [
  'generated by',
  'generated with',
  'co-authored-by: claude',
  'co-authored-by: chatgpt',
  'co-authored-by: gpt-',
  'co-authored-by: copilot',
  'co-authored-by: cursor',
  'co-authored-by: aider',
  'co-authored-by: codeium',
  '[skip ci] auto-generated',
  '(assisted by ai)',
  'ai-generated',
  'created by chatgpt',
  'written by claude',
];

// Weight per signal. Chosen so that any ONE strong signal (message marker or
// 5x-median diff) yields >= 0.5, but no single signal saturates to 1.0. Only
// two-plus signals should land above 0.9.
const SIGNAL_WEIGHT = {
  messageMarker: 0.55,
  largeDiffMultiplier: 0.35, // scaled by how many multiples of the median
  manyUnrelatedFiles: 0.25,
  suspiciousBurstiness: 0.20, // repeated identical-shape commits in the same second
};

// Hard-coded floors used when we have no author median to compare against.
const DEFAULT_LINES_MEDIAN = 40;
const DEFAULT_FILES_MEDIAN = 3;
// Above this multiple of the median, the diff-size signal fires.
const DIFF_MULTIPLE_TRIGGER = 5;
// Above this file count, the "many unrelated files" signal fires — a proxy
// for AI cross-cutting changes.
const UNRELATED_FILES_TRIGGER = 20;

/**
 * Score a single commit. Deterministic and pure.
 */
export function scoreCommit(
  commit: CommitStat,
  opts: AiAssistHeuristicOptions = {},
): AiAssistScore {
  const reasons: string[] = [];
  let raw = 0;

  const msg = commit.message.toLowerCase();
  const marker = AI_MESSAGE_MARKERS.find((m) => msg.includes(m));
  if (marker) {
    raw += SIGNAL_WEIGHT.messageMarker;
    reasons.push(`message marker: "${marker}"`);
  }

  const linesMedian = opts.authorMedianLinesChanged ?? DEFAULT_LINES_MEDIAN;
  const changed = commit.additions + commit.deletions;
  if (linesMedian > 0 && changed >= linesMedian * DIFF_MULTIPLE_TRIGGER) {
    const multiple = changed / linesMedian;
    // Scale the diff-size signal by how many multiples of the median we saw,
    // capped so a truly enormous refactor doesn't override the message signal.
    const scaled = Math.min(
      SIGNAL_WEIGHT.largeDiffMultiplier,
      SIGNAL_WEIGHT.largeDiffMultiplier * (multiple / (DIFF_MULTIPLE_TRIGGER * 2)),
    );
    raw += scaled;
    reasons.push(
      `diff ${changed} lines is ${multiple.toFixed(1)}x author median (${linesMedian})`,
    );
  }

  const filesMedian = opts.authorMedianFilesTouched ?? DEFAULT_FILES_MEDIAN;
  if (
    commit.filesTouched >= UNRELATED_FILES_TRIGGER ||
    (filesMedian > 0 && commit.filesTouched >= filesMedian * DIFF_MULTIPLE_TRIGGER)
  ) {
    raw += SIGNAL_WEIGHT.manyUnrelatedFiles;
    reasons.push(`${commit.filesTouched} files touched (author median ${filesMedian})`);
  }

  // Squash to [0..1] with a soft ceiling so multi-signal commits saturate,
  // but no single signal reaches 1.
  const confidence = clampUnit(raw);
  return { confidence, reasons };
}

/**
 * Score a batch of commits. Reuses medians computed once across the batch
 * when caller hasn't supplied them. Also flags "burstiness": several commits
 * with the same authored second get a small confidence bump each, since AI
 * agents often emit multi-commit sequences within one wall-clock second.
 */
export function scoreCommitBatch(
  commits: CommitStat[],
  opts: AiAssistHeuristicOptions = {},
): Array<AiAssistScore & { sha: string }> {
  const linesMedian = opts.authorMedianLinesChanged ?? median(
    commits.map((c) => c.additions + c.deletions),
  );
  const filesMedian = opts.authorMedianFilesTouched ?? median(
    commits.map((c) => c.filesTouched),
  );

  // Count commits per authored second to detect burstiness.
  const perSecond = new Map<string, number>();
  for (const c of commits) {
    const key = `${c.authorEmail}|${Math.floor(c.authoredAt.getTime() / 1000)}`;
    perSecond.set(key, (perSecond.get(key) ?? 0) + 1);
  }

  return commits.map((c) => {
    const base = scoreCommit(c, {
      authorMedianLinesChanged: linesMedian,
      authorMedianFilesTouched: filesMedian,
    });
    const key = `${c.authorEmail}|${Math.floor(c.authoredAt.getTime() / 1000)}`;
    const bucket = perSecond.get(key) ?? 1;
    if (bucket >= 3) {
      return {
        sha: c.sha,
        confidence: clampUnit(base.confidence + SIGNAL_WEIGHT.suspiciousBurstiness),
        reasons: [...base.reasons, `${bucket} commits authored in the same second`],
      };
    }
    return { sha: c.sha, confidence: base.confidence, reasons: base.reasons };
  });
}

// --- helpers (exported for tests) ---

export function median(nums: number[]): number {
  if (nums.length === 0) return 0;
  const sorted = [...nums].sort((a, b) => a - b);
  const mid = Math.floor(sorted.length / 2);
  return sorted.length % 2 === 0
    ? (sorted[mid - 1]! + sorted[mid]!) / 2
    : sorted[mid]!;
}

function clampUnit(n: number): number {
  return Math.max(0, Math.min(1, n));
}
