import { describe, it, expect } from 'vitest';
import {
  scoreCommit,
  scoreCommitBatch,
  median,
  AI_MESSAGE_MARKERS,
  type CommitStat,
} from './ai-assist-heuristic';

function make(overrides: Partial<CommitStat> = {}): CommitStat {
  return {
    sha: overrides.sha ?? 'abc',
    message: overrides.message ?? 'fix: null-guard the loader',
    filesTouched: overrides.filesTouched ?? 2,
    additions: overrides.additions ?? 10,
    deletions: overrides.deletions ?? 3,
    authorEmail: overrides.authorEmail ?? 'me@example.com',
    authoredAt: overrides.authoredAt ?? new Date('2026-01-01T00:00:00Z'),
  };
}

describe('median', () => {
  it('handles odd + even lengths', () => {
    expect(median([1, 2, 3])).toBe(2);
    expect(median([1, 2, 3, 4])).toBe(2.5);
  });
  it('empty is zero', () => {
    expect(median([])).toBe(0);
  });
});

describe('scoreCommit', () => {
  it('scores a normal commit near zero', () => {
    const s = scoreCommit(make());
    expect(s.confidence).toBe(0);
    expect(s.reasons).toEqual([]);
  });

  it('fires on a Co-Authored-By: Claude marker', () => {
    const s = scoreCommit(
      make({ message: 'feat: add caching\n\nCo-Authored-By: Claude <noreply@anthropic.com>' }),
    );
    expect(s.confidence).toBeGreaterThanOrEqual(0.5);
    expect(s.reasons.some((r) => r.includes('marker'))).toBe(true);
  });

  it('fires on a huge diff vs. median', () => {
    const s = scoreCommit(
      make({ additions: 5000, deletions: 100 }),
      { authorMedianLinesChanged: 40 },
    );
    expect(s.confidence).toBeGreaterThan(0);
    expect(s.reasons.some((r) => r.includes('median'))).toBe(true);
  });

  it('fires on many-files-touched trigger', () => {
    const s = scoreCommit(make({ filesTouched: 40 }));
    expect(s.confidence).toBeGreaterThan(0);
    expect(s.reasons.some((r) => r.includes('files'))).toBe(true);
  });

  it('multi-signal commits saturate to 1', () => {
    const s = scoreCommit(
      make({
        message: 'chore: sweeping refactor\n\nGenerated by ChatGPT',
        additions: 8000,
        deletions: 200,
        filesTouched: 60,
      }),
      { authorMedianLinesChanged: 40, authorMedianFilesTouched: 3 },
    );
    expect(s.confidence).toBeCloseTo(1, 3);
    expect(s.reasons.length).toBeGreaterThanOrEqual(3);
  });

  it('confidence is always in [0..1]', () => {
    const s = scoreCommit(
      make({ additions: 1e6, deletions: 1e6, filesTouched: 1e6, message: 'generated by' }),
    );
    expect(s.confidence).toBeGreaterThanOrEqual(0);
    expect(s.confidence).toBeLessThanOrEqual(1);
  });

  it('has a non-empty marker list', () => {
    expect(AI_MESSAGE_MARKERS.length).toBeGreaterThan(5);
  });
});

describe('scoreCommitBatch', () => {
  it('adds burstiness signal when >= 3 commits share the same authored second', () => {
    const t = new Date('2026-01-01T00:00:00.000Z');
    const batch = [
      make({ sha: '1', authoredAt: t }),
      make({ sha: '2', authoredAt: t }),
      make({ sha: '3', authoredAt: t }),
    ];
    const scores = scoreCommitBatch(batch);
    for (const s of scores) {
      expect(s.confidence).toBeGreaterThan(0);
      expect(s.reasons.some((r) => r.includes('same second'))).toBe(true);
    }
  });

  it('leaves solo commits unbursted', () => {
    const scores = scoreCommitBatch([make()]);
    expect(scores[0]!.confidence).toBe(0);
  });

  it('derives medians when not supplied', () => {
    const batch = [
      make({ sha: '1', additions: 10, deletions: 0, filesTouched: 1 }),
      make({ sha: '2', additions: 10, deletions: 0, filesTouched: 1 }),
      make({
        sha: '3',
        additions: 500, // 50x the median of 10
        deletions: 0,
        filesTouched: 1,
      }),
    ];
    const scores = scoreCommitBatch(batch);
    // The huge one gets a diff-size signal even though no medians were passed.
    const big = scores.find((s) => s.sha === '3')!;
    expect(big.confidence).toBeGreaterThan(0);
  });
});
