// Gmail/outbound MIME construction, shared by the API (draft creation) and any
// future producer. Pure string work: no googleapis, no HTTP, no Prisma. That
// keeps this package dependency-free (AGENTS.md §6) while giving both the API
// and worker one correct RFC 5322 encoder instead of two hand-rolled ones.
//
// Scope: plain-text bodies only. Outreach mail is intentionally plain (see
// `outreach-composer` prompt: "plain text; a blank line between paragraphs"),
// so multipart/alternative is unrequested complexity. When HTML outreach
// lands, add multipart here and both callers get it.

export interface OutboundEmail {
  /** RFC 5322 mailbox, e.g. `Jane <jane@acme.com>` or `jane@acme.com`. */
  to: string;
  subject: string;
  body: string;
  /** Optional From; Gmail fills in the authenticated account when omitted. */
  from?: string;
  /** Threading headers for replies. */
  inReplyTo?: string;
  references?: string[];
  /** Caller-supplied stable Message-ID. Auto-generated by Gmail when omitted. */
  messageId?: string;
  /** Injectable clock for deterministic tests. */
  date?: Date;
}

/**
 * Strip CR/LF (and NUL) so a crafted value can never inject a header. This is
 * the single most important MIME-safety control: an unescaped `\r\nBcc:` in a
 * recipient or subject is a header-injection vuln.
 */
export function sanitizeHeaderValue(value: string): string {
  return value.replace(/[\r\n\0]+/g, ' ').trim();
}

/** RFC 2047 encoded-word for non-ASCII header text, else the sanitized value. */
export function encodeHeaderText(value: string): string {
  const clean = sanitizeHeaderValue(value);
  // eslint-disable-next-line no-control-regex
  if (/^[\x20-\x7e]*$/.test(clean)) return clean;
  return `=?UTF-8?B?${Buffer.from(clean, 'utf8').toString('base64')}?=`;
}

/** Wrap a base64 body at 76 chars per RFC 2045 §6.8. */
export function foldBase64(b64: string): string {
  return b64.replace(/.{76}/g, '$&\r\n');
}

/** Deterministic Message-ID derived from a stable seed (idempotency aid). */
export function deterministicMessageId(seed: string, domain = 'careeros.local'): string {
  const hash = createHashLike(seed);
  return `<${hash}@${sanitizeHeaderValue(domain)}>`;
}

/**
 * Build a complete RFC 5322 message with a UTF-8 text/plain body. Header names
 * are emitted in a stable order so the output is byte-stable for a given input
 * (tests + idempotency rely on that).
 */
export function buildRfc822Message(email: OutboundEmail): string {
  const date = email.date ?? new Date();
  const headers: string[] = [];
  if (email.from) headers.push(`From: ${sanitizeHeaderValue(email.from)}`);
  headers.push(`To: ${sanitizeHeaderValue(email.to)}`);
  headers.push(`Subject: ${encodeHeaderText(email.subject)}`);
  headers.push(`Date: ${date.toUTCString()}`);
  if (email.messageId) headers.push(`Message-ID: ${sanitizeHeaderValue(email.messageId)}`);
  if (email.inReplyTo) headers.push(`In-Reply-To: ${sanitizeHeaderValue(email.inReplyTo)}`);
  if (email.references && email.references.length > 0) {
    headers.push(
      `References: ${email.references.map(sanitizeHeaderValue).join(' ')}`,
    );
  }
  headers.push('MIME-Version: 1.0');
  headers.push('Content-Type: text/plain; charset="UTF-8"');
  headers.push('Content-Transfer-Encoding: base64');

  const body = foldBase64(Buffer.from(normalizeNewlines(email.body), 'utf8').toString('base64'));
  // RFC 5322 requires CRLF between headers and a blank line before the body.
  return `${headers.join('\r\n')}\r\n\r\n${body}\r\n`;
}

/** Encode an RFC 5322 message for the Gmail API `raw` field (base64url). */
export function encodeRawMessage(raw: string): string {
  return Buffer.from(raw, 'utf8')
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/** Normalize any newline style to CRLF (SMTP canonical form). */
function normalizeNewlines(s: string): string {
  return s.replace(/\r\n|\r|\n/g, '\r\n');
}

/**
 * Tiny non-crypto digest used only to derive a stable Message-ID. `node:crypto`
 * is available everywhere this runs, but a deterministic 32-hex FNV-ish hash
 * keeps the helper dependency-free and constant across processes/languages.
 */
function createHashLike(seed: string): string {
  let h1 = 0x811c9dc5;
  let h2 = 0x01000193;
  for (let i = 0; i < seed.length; i++) {
    const c = seed.charCodeAt(i);
    h1 = Math.imul(h1 ^ c, 0x01000193) >>> 0;
    h2 = Math.imul(h2 ^ c, 0x85ebca6b) >>> 0;
  }
  return (h1.toString(16).padStart(8, '0') + h2.toString(16).padStart(8, '0'));
}
